analytics-cli:
  build: .
  command: node server
  ports:
    - "3000:3000"
  volumes:
    - ./:/app/analytics-cli
  links:
    - db:db


db:
  image: mysql:5.7
  environment:
    MYSQL_ROOT_PASSWORD: tarantula
    MYSQL_DATABASE: tarantula
    MYSQL_USER: tarantula
    MYSQL_PASSWORD: tarantula
  volumes:
    - ./:/app/
